#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
    NRNHOME="/home/kharms/.local/lib/python3.8/site-packages/neuron/.data"
fi
if test "${NEURONHOME}" = "" ; then
    NEURONHOME=${NRNHOME}/share/nrn
    export NEURONHOME
fi
if test "x${NRNBIN}" = "x" ; then
    NRNBIN="/home/kharms/.local/bin"
fi
if test "" = "yes" ; then
    NRNIV="${NRNBIN}/nrniv.app/Contents/MacOS/nrniv"
else
    NRNIV="${NRNBIN}/nrniv"
fi
"${NRNIV}" -dll "/home/kharms/c302/test_cell_just_soma/x86_64/.libs/libnrnmech.so" "$@"
